# Prompt optimization experiment configuration
script: "optimize-prompt"
continue_on_failure: true

# Fixed arguments for all runs
fixed_args:
  task: "rephrase"

  qos: "high"
  time: "7-00:00:00"
  
  train-size: 500
  val-size: 250
  test-size: 500

# Variable arguments - creates different experiment runs
runs:
  #- name: "new-score-clipped-feedback"
  #  args:
  #    generation-model: "huggingface/google/gemma-3-27b-it"
  #    budget: 10
  #- name: "new-score-clipped-feedback"
  #  args:
  #    generation-model: "huggingface/google/gemma-3-27b-it"
  #    val-size: 200
  #    budget: 20
  #- name: "test"
  #  args:
  #    generation-model: "huggingface/google/gemma-3-27b-it"
  #    budget: 1
  #- name: "test"
  #  args:
  #    generation-model: "huggingface/google/gemma-3-27b-it"
  #    budget: 10
  #- name: "test"
  #  args:
  #    generation-model: "huggingface/google/gemma-3-27b-it"
  #    budget: 20

  #- name: "new-score-clipped-feedback"
  #  args:
  #    generation-model: "huggingface/google/gemma-3-12b-it"
  #    budget: 1
  #- name: "new-score-clipped-feedback"
  #  args:
  #    generation-model: "huggingface/google/gemma-3-12b-it"
  #    budget: 10
  #- name: "new-score-clipped-feedback"
  #  args:
  #    generation-model: "huggingface/google/gemma-3-12b-it"
  #    budget: 20
  #- name: "new-score-clipped-feedback"
  #  args:
  #    generation-model: "huggingface/google/gemma-3-12b-it"
  #    budget: 50
  #- name: "test"
  #  args:
  #    generation-model: "huggingface/google/gemma-3-12b-it"
  #    budget: 1
  #- name: "test"
  #  args:
  #    generation-model: "huggingface/google/gemma-3-12b-it"
  #    budget: 10
  #- name: "test"
  #  args:
  #    generation-model: "huggingface/google/gemma-3-12b-it"
  #    budget: 20

  #- name: "new-score-clipped-feedback"
  #  args:
  #    generation-model: "huggingface/google/gemma-3-4b-it"
  #    budget: 1
  #- name: "new-score-clipped-feedback"
  #  args:
  #    generation-model: "huggingface/google/gemma-3-4b-it"
  #    budget: 10
  #- name: "new-score-clipped-feedback"
  #  args:
  #    generation-model: "huggingface/google/gemma-3-4b-it"
  #    budget: 20
  #- name: "new-score-clipped-feedback"
  #  args:
  #    generation-model: "huggingface/google/gemma-3-4b-it"
  #    budget: 50
  #- name: "test"
  #  args:
  #    generation-model: "huggingface/google/gemma-3-4b-it"
  #    budget: 1
  #- name: "test"
  #  args:
  #    generation-model: "huggingface/google/gemma-3-4b-it"
  #    budget: 10
  #- name: "test"
  #  args:
  #    generation-model: "huggingface/google/gemma-3-4b-it"
  #    budget: 20

  #- name: "new-score-clipped-feedback"
  #  args:
  #    generation-model: "huggingface/google/gemma-3-1b-it"
  #    budget: 1
  #- name: "new-score-clipped-feedback"
  #  args:
  #    generation-model: "huggingface/google/gemma-3-1b-it"
  #    budget: 10
  #- name: "new-score-clipped-feedback"
  #  args:
  #    generation-model: "huggingface/google/gemma-3-1b-it"
  #    budget: 20
  #- name: "new-score-clipped-feedback"
  #  args:
  #    generation-model: "huggingface/google/gemma-3-1b-it"
  #    budget: 50
  #- name: "test"
  #  args:
  #    generation-model: "huggingface/google/gemma-3-1b-it"
  #    budget: 1
  #- name: "test"
  #  args:
  #    generation-model: "huggingface/google/gemma-3-1b-it"
  #    budget: 20

  #- name: "test"
  #  args:
  #    generation-model: "huggingface/google/gemma-3-270m-it"
  #    budget: 1
  #- name: "test"
  #  args:
  #    generation-model: "huggingface/google/gemma-3-270m-it"
  #    budget: 10
  #- name: "test"
  #  args:
  #    generation-model: "huggingface/google/gemma-3-270m-it"
  #    budget: 20
