# Rephrasing benchmark experiment configuration
script: "rephrase"
continue_on_failure: true

# IMPORTANT: This is a large run, make sure to inform people in #science-cluster-planning beforehand.

# Fixed arguments for all runs
fixed_args:
  # Data and output configuration
  data-paths: "s3://finephrase/experiments/filtered/fineweb-edu-lq-20BT"
  limit: -1
  
  # Processing configuration
  enable-prefix-caching: true
  enable-chunked-prefill: true

  # Model configuration 
  max-tokens: 4096
  model-max-context: 16384

  temperature: 1
  top-p: 0.95
  top-k: 64
  
  # Infrastructure configuration
  max-concurrent-requests: 500
  max-concurrent-tasks: 500
  gpu-memory-utilization: 0.97 # 0.98 can sometimes OOM
  server-type: "vllm"
  
  # Debugging and checkpoints
  debug: false # Logs get very verbose when debug is true
  
  # Slurm configuration
  time: "3-00:00:00"
  qos: "low"
  n-tasks: 1000 # The input dataset has 10K chunks, so we cannot run more tasks (2M tokens per file)
  #n-workers: 16 # Only limit the number of workers if you are running in qos normal

# There is usually more input tokens than output tokens
# 27B (tp4): ~4.5M output tokens per hour 
# 12B (tp2): ~3.6M output tokens per hour 
# 4B (tp1): ~7.2M output tokens per hour
# 1B (tp1): ~33.2M output tokens per hour 
# 270M (tp1): ~62.4M output tokens per hour

# Variable arguments - creates different experiment runs
runs:
  #- name: "test"
  #  args:
  #    model-name-or-path: "google/gemma-3-27b-it"
  #    prompt: "dspy/rephrase/gemma-3-27b-it/budget-1.md"
  #    tp: 4
  - name: "test"
    args:
      model-name-or-path: "google/gemma-3-27b-it"
      prompt: "dspy/rephrase/gemma-3-27b-it/budget-10.md"
      tp: 4

  #- name: "test"
  #  args:
  #    model-name-or-path: "google/gemma-3-4b-it"
  #    prompt: "dspy/rephrase/gemma-3-4b-it/budget-1.md"
  #    tp: 1
  #- name: "test"
  #  args:
  #    model-name-or-path: "google/gemma-3-4b-it"
  #    prompt: "dspy/rephrase/gemma-3-4b-it/budget-10.md"
  #    tp: 1

  #- name: "test"
  #  args:
  #    model-name-or-path: "google/gemma-3-1b-it"
  #    prompt: "dspy/rephrase/gemma-3-1b-it/budget-1.md"
  #    tp: 1
  #- name: "test"
  #  args:
  #    model-name-or-path: "google/gemma-3-1b-it"
  #    prompt: "dspy/rephrase/gemma-3-1b-it/budget-10.md"
  #    tp: 1
