# Rephrasing benchmark experiment configuration
script: "rephrase"
continue_on_failure: true

# Fixed arguments for all runs
fixed_args:
  # Data and output configuration
  data-paths: "s3://finephrase/experiments/filtered/fineweb-edu-lq-20BT"
  limit: 1000 # TODO: remove this when i am sure
  
  # Processing configuration
  enable-prefix-caching: true
  enable-chunked-prefill: true

  # Model configuration 
  max-tokens: 4096
  model-max-context: 16384

  temperature: 1
  top-p: 0.95
  top-k: 64
  
  # Infrastructure configuration
  max-concurrent-requests: 500
  max-concurrent-tasks: 500
  gpu-memory-utilization: 0.97
  server-type: "vllm"
  
  # Debugging and checkpoints
  debug: false # Logs get very verbose when debug is true
  tokenizer: "hynky/Llama-3.2-1B-no-bos"
  
  # Slurm configuration
  time: "23:00:00"
  qos: "normal"
  n-tasks: 10

# Variable arguments - creates different experiment runs
runs:
  #- name: "gemma_3_270m_it"
  #  args:
  #    model-name-or-path: "google/gemma-3-270m-it"
  #    gpus: 1
  #    tp: 1
  - name: "gemma_3_27b_it_budget_1"
    args:
      model-name-or-path: "google/gemma-3-27b-it"
      prompt: "dspy/rephrase/gemma-3-27b-it/budget-1.md"
      gpus: 4
      tp: 4

  - name: "gemma_3_27b_it_budget_10"
    args:
      model-name-or-path: "google/gemma-3-27b-it"
      prompt: "dspy/rephrase/gemma-3-27b-it/budget-10.md"
      gpus: 4
      tp: 4